run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    # Enabled by default
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Reports suspicious constructs
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Advanced go vet
    - unused        # Checks for unused code

    # Additional recommended linters
    - gofmt         # Checks code formatting
    - goimports     # Checks import formatting
    - misspell      # Finds commonly misspelled English words
    - revive        # Fast, configurable, extensible linter
    - unconvert     # Removes unnecessary type conversions
    - unparam       # Reports unused function parameters
    - gosec         # Security-focused linter
    - gocritic      # Provides diagnostics for code quality

  disable:
    - typecheck     # Can have false positives with generated code

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (*github.com/hashicorp/terraform-plugin-log/tflog.Logger).Debug
      - (*github.com/hashicorp/terraform-plugin-log/tflog.Logger).Info
      - (*github.com/hashicorp/terraform-plugin-log/tflog.Logger).Warn

  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too strict for this codebase
      - shadow         # Can be overly sensitive

  gofmt:
    simplify: true

  goimports:
    local-prefixes: ronati-terraform-typesense

  misspell:
    locale: US

  revive:
    rules:
      - name: var-naming
        disabled: true  # Terraform uses snake_case for some variables
      - name: exported
        disabled: true  # Not all exported items need comments initially

  gosec:
    excludes:
      - G104  # Audit errors not checked (covered by errcheck)
      - G304  # File path provided as taint input (needed for tests)

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - gocritic
        - unparam
        - errcheck

    # Exclude specific linters for generated files
    - path: ".*\\.pb\\.go"
      linters:
        - all

    # Allow long lines in tests for readability
    - path: _test\.go
      linters:
        - lll

  # Maximum issues count per one linter
  max-issues-per-linter: 0

  # Maximum count of issues with the same text
  max-same-issues: 0

  # Show all issues from a linter
  new: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
